services:
  node:
    build:
      context: node
    container_name: nginx-node-app
    networks:
      - node-nginx-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build:
      context: nginx
    container_name: nginx-node
    networks:
      - node-nginx-network
    ports:
      - "8080:80"

networks:
  node-nginx-network:
    driver: bridge